#################################################
# Dockerfile to build bastion container images
# Based on Ubuntu
##################################################

#set the base image to ubuntu
FROM ubuntu

#run something
RUN echo "hello docker"

