#################################################
# Dockerfile to build bastion container images
# Based on Ubuntu
##################################################

#set the base image to ubuntu
FROM ubuntu

#get phantomjs and pip
RUN apt-get -y install phantomjs python-pip

#get selenium 
RUN pip install selenium 

#get flask
RUN pip install flask



